route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token_file: /etc/alertmanager/telegram.env
      chat_id: $ALM_TELEGRAM_CHAT_ID
      message: {{ template "tg.message" . }}

templates:
- '/etc/alertmanager/template/telegram.tmpl'
