---
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: foobar
    isDefault: true
    editable: true
